version: '3.8'

services:
  app:
    build: .
    container_name: Final_Web_Project
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: Final_Web_Project-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event_management
      MYSQL_USER: Final_Web_Project
      MYSQL_PASSWORD: Final_Web_Project662025
    ports:
      - "5432:3300"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Final_Web_Project-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Final_Web_Project662025
    depends_on:
      - db

volumes:
  db_data:
