version: '3.8'

services:
  app:
    build: .
    container_name: Final_Web_Project
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: Final_Web_Project-postgres
    restart: always
    environment:
      POSTGRES_USER: final_web_project
      POSTGRES_PASSWORD: jJTAEJ1WJf2wRV4c7TvF8owsEDEMd372
      POSTGRES_DB: event_management_ebim
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: